 CLASS zi_rap_t003_header_test  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zi_rap_t003_header_test  IMPLEMENTATION.
 ENDCLASS.
